### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Kgomotso196** [Rifat8080/Portfolio-site#7]
Hello @Rifat8080 , kindly align the contact desc and form based on the above cards to stick to the Figma design and have a better UI.
![Screenshot (191)](https://github.com/Rifat8080/Portfolio-site/assets/74494438/665ebd2b-b778-4901-95d4-210b549a7f5f)

**Comment by olanikegloria** [comment]
Hello Rifat you have done such a great and unique work. I  do not  have much to say other than its really nice but I would also suggest that the header should be fixed so that it does not clash with the texts while scrolling

**Comment by Shabiblac** [comment]
Great work ✔️ 

kindly consider fixing the navigation bar to improve the UI of the webpage 😄

**Comment by Kgomotso196** [comment]
Other than the mentioned suggestions above, I'm really impressed by your work. Good job.🎉
